"""initial marketplace schema

Revision ID: 8e82246948e7
Revises: 
Create Date: 2026-09-01 10:44:51.152989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e82246948e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_throttle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('window_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_throttle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_throttle_key_hash'), ['key_hash'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'co_admin', 'user', 'developer', name='userrole', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'blocked', 'deleted', name='accountstatus', native_enum=False, length=20), nullable=False),
    sa.Column('company_name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status_before_delete', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('co_admin_management', 'account_moderation', 'app_moderation', 'release_moderation', 'report_moderation', 'review_moderation', name='auditaction', native_enum=False, length=40), nullable=False),
    sa.Column('operation', sa.String(length=30), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('target_label', sa.String(length=180), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_target_type'), ['target_type'], unique=False)

    op.create_table('developer_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('legal_name', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('government_id_type', sa.Enum('national_id', 'passport', 'driving_license', 'voter_id', name='governmentidtype', native_enum=False, length=30), nullable=True),
    sa.Column('government_id_number', sa.String(length=80), nullable=True),
    sa.Column('government_id_file', sa.String(length=255), nullable=True),
    sa.Column('government_id_original_name', sa.String(length=255), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('developer_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_developer_profile_user_id'), ['user_id'], unique=True)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('account', 'app', 'release', name='notificationtype', native_enum=False, length=20), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_type'), ['type'], unique=False)

    op.create_table('password_reset_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_token_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_token_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_reset_token_user_id'), ['user_id'], unique=False)

    op.create_table('store_app',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('package_name', sa.String(length=180), nullable=False),
    sa.Column('short_description', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('min_android_version', sa.String(length=40), nullable=False),
    sa.Column('category', sa.Enum('business', 'education', 'entertainment', 'finance', 'games', 'health', 'lifestyle', 'productivity', 'social', 'tools', 'other', name='appcategory', native_enum=False, length=30), nullable=False),
    sa.Column('age_rating', sa.Enum('everyone', 'teen', 'mature', name='agerating', native_enum=False, length=20), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('support_email', sa.String(length=120), nullable=False),
    sa.Column('privacy_policy_url', sa.String(length=255), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('icon_file', sa.String(length=255), nullable=False),
    sa.Column('apk_file', sa.String(length=255), nullable=False),
    sa.Column('apk_original_name', sa.String(length=255), nullable=False),
    sa.Column('apk_size', sa.Integer(), nullable=False),
    sa.Column('apk_sha256', sa.String(length=64), nullable=False),
    sa.Column('security_scan_status', sa.Enum('unscanned', 'passed', 'failed', name='securityscanstatus', native_enum=False, length=20), nullable=False),
    sa.Column('security_scan_summary', sa.Text(), nullable=True),
    sa.Column('security_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('malware_scan_status', sa.Enum('unscanned', 'passed', 'failed', name='securityscanstatus', native_enum=False, length=20), nullable=False),
    sa.Column('malware_scan_summary', sa.Text(), nullable=True),
    sa.Column('malware_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pending_version', sa.String(length=40), nullable=True),
    sa.Column('pending_min_android_version', sa.String(length=40), nullable=True),
    sa.Column('pending_changelog', sa.Text(), nullable=True),
    sa.Column('pending_apk_file', sa.String(length=255), nullable=True),
    sa.Column('pending_apk_original_name', sa.String(length=255), nullable=True),
    sa.Column('pending_apk_size', sa.Integer(), nullable=True),
    sa.Column('pending_apk_sha256', sa.String(length=64), nullable=True),
    sa.Column('pending_security_scan_status', sa.Enum('unscanned', 'passed', 'failed', name='securityscanstatus', native_enum=False, length=20), nullable=True),
    sa.Column('pending_security_scan_summary', sa.Text(), nullable=True),
    sa.Column('pending_security_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pending_malware_scan_status', sa.Enum('unscanned', 'passed', 'failed', name='securityscanstatus', native_enum=False, length=20), nullable=True),
    sa.Column('pending_malware_scan_summary', sa.Text(), nullable=True),
    sa.Column('pending_malware_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pending_release_status', sa.Enum('pending', 'rejected', name='releasestatus', native_enum=False, length=20), nullable=True),
    sa.Column('pending_release_note', sa.Text(), nullable=True),
    sa.Column('pending_release_submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'blocked', 'deleted', name='appstatus', native_enum=False, length=20), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status_before_delete', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['developer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('store_app', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_app_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_store_app_developer_id'), ['developer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_store_app_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_store_app_package_name'), ['package_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_store_app_pending_release_status'), ['pending_release_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_store_app_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_store_app_status'), ['status'], unique=False)

    op.create_table('app_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('malware', 'privacy', 'inappropriate', 'copyright', 'misleading', 'other', name='reportreason', native_enum=False, length=30), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'resolved', 'dismissed', name='reportstatus', native_enum=False, length=20), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['store_app.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_report', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_report_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_report_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_report_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_report_user_id'), ['user_id'], unique=False)

    op.create_table('app_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('published', 'hidden', name='reviewstatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_app_review_rating'),
    sa.ForeignKeyConstraint(['app_id'], ['store_app.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'app_id', name='uq_app_review_user_app')
    )
    with op.batch_alter_table('app_review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_review_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_review_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_review_user_id'), ['user_id'], unique=False)

    op.create_table('app_screenshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['store_app.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_screenshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_screenshot_app_id'), ['app_id'], unique=False)

    op.create_table('app_version_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('min_android_version', sa.String(length=40), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('apk_file', sa.String(length=255), nullable=False),
    sa.Column('apk_original_name', sa.String(length=255), nullable=False),
    sa.Column('apk_size', sa.Integer(), nullable=False),
    sa.Column('apk_sha256', sa.String(length=64), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['store_app.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_version_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_version_history_app_id'), ['app_id'], unique=False)

    op.create_table('download_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['store_app.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('download_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_download_record_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_download_record_downloaded_at'), ['downloaded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_download_record_user_id'), ['user_id'], unique=False)

    op.create_table('saved_app',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['store_app.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'app_id', name='uq_saved_app_user_app')
    )
    with op.batch_alter_table('saved_app', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_app_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_app_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_app', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_app_user_id'))
        batch_op.drop_index(batch_op.f('ix_saved_app_app_id'))

    op.drop_table('saved_app')
    with op.batch_alter_table('download_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_download_record_user_id'))
        batch_op.drop_index(batch_op.f('ix_download_record_downloaded_at'))
        batch_op.drop_index(batch_op.f('ix_download_record_app_id'))

    op.drop_table('download_record')
    with op.batch_alter_table('app_version_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_version_history_app_id'))

    op.drop_table('app_version_history')
    with op.batch_alter_table('app_screenshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_screenshot_app_id'))

    op.drop_table('app_screenshot')
    with op.batch_alter_table('app_review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_review_user_id'))
        batch_op.drop_index(batch_op.f('ix_app_review_status'))
        batch_op.drop_index(batch_op.f('ix_app_review_app_id'))

    op.drop_table('app_review')
    with op.batch_alter_table('app_report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_report_user_id'))
        batch_op.drop_index(batch_op.f('ix_app_report_status'))
        batch_op.drop_index(batch_op.f('ix_app_report_created_at'))
        batch_op.drop_index(batch_op.f('ix_app_report_app_id'))

    op.drop_table('app_report')
    with op.batch_alter_table('store_app', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_app_status'))
        batch_op.drop_index(batch_op.f('ix_store_app_slug'))
        batch_op.drop_index(batch_op.f('ix_store_app_pending_release_status'))
        batch_op.drop_index(batch_op.f('ix_store_app_package_name'))
        batch_op.drop_index(batch_op.f('ix_store_app_name'))
        batch_op.drop_index(batch_op.f('ix_store_app_developer_id'))
        batch_op.drop_index(batch_op.f('ix_store_app_category'))

    op.drop_table('store_app')
    with op.batch_alter_table('password_reset_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_token_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_token_token_hash'))
        batch_op.drop_index(batch_op.f('ix_password_reset_token_expires_at'))

    op.drop_table('password_reset_token')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_type'))
        batch_op.drop_index(batch_op.f('ix_notification_recipient_id'))
        batch_op.drop_index(batch_op.f('ix_notification_is_read'))
        batch_op.drop_index(batch_op.f('ix_notification_created_at'))

    op.drop_table('notification')
    with op.batch_alter_table('developer_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_developer_profile_user_id'))

    op.drop_table('developer_profile')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_target_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_admin_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_status'))
        batch_op.drop_index(batch_op.f('ix_user_role'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('login_throttle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_throttle_key_hash'))

    op.drop_table('login_throttle')
    # ### end Alembic commands ###
